export const supabaseUrl= 'https://vzxvsnyprfzsopgttksf.supabase.co'

export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6eHZzbnlwcmZ6c29wZ3R0a3NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA2NDIwNDIsImV4cCI6MjA0NjIxODA0Mn0.xQTb7ayxq-pX9qLDHAzRVVfFFNLFhgTvQo3kVbPddCc'